import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
// import { CameraProvider } from "@/context/user-camera-context";
import { ScrollArea } from "@radix-ui/react-scroll-area";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Mango Lens",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icon/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {/* <CameraProvider>
              <CaptureImageProvider> */}
                <ScrollArea>{children}</ScrollArea>
              {/* </CaptureImageProvider>
            </CameraProvider> */}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
